CMAKE_CXX_STANDARD = "17"
LLVM_VERSION_MAJOR = "21"
LLVM_VERSION_MINOR = "0"
LLVM_VERSION_PATCH = "0"
LLVM_VERSION_SUFFIX = ""
LLVM_VERSION = "21.0.0"

llvm_vars={
    "CMAKE_CXX_STANDARD": "17",
    "LLVM_VERSION_MAJOR": "21",
    "LLVM_VERSION_MINOR": "0",
    "LLVM_VERSION_PATCH": "0",
    "LLVM_VERSION": "21.0.0",
}

PACKAGE_VERSION="bazel-build"
