# Generated from llvm/CMakeLists.txt

CMAKE_CXX_STANDARD = "17"
LLVM_VERSION_MAJOR = "20"
LLVM_VERSION_MINOR = "1"
LLVM_VERSION_PATCH = "8"
LLVM_VERSION_SUFFIX = ""
LLVM_VERSION = "20.1.8"
PACKAGE_VERSION = "20.1.8"

llvm_vars={
    "CMAKE_CXX_STANDARD": "17",
    "LLVM_VERSION_MAJOR": "20",
    "LLVM_VERSION_MINOR": "1",
    "LLVM_VERSION_PATCH": "8",
    "LLVM_VERSION_SUFFIX": "",
    "LLVM_VERSION": "20.1.8",
    "PACKAGE_VERSION": "20.1.8",
}
